In [1]:
import pandas as pd
from matplotlib.ticker import MaxNLocator
%matplotlib qt5
from matplotlib import pyplot as plt

plt.rcParams.update({'font.size': 10,'font.family':'serif','font.serif':'Arial'})

In [54]:
data7 = 'RBE_ctd_7_oct.xlsx'
df7 = pd.read_excel(data7)

In [57]:
data11 = 'RBE_ctd_11_okt.xlsx'
df11 = pd.read_excel(data11)

In [59]:
df11.describe().T

,count,mean,min,25%,50%,75%,max,std
Time,7753,2023-10-11 08:20:08.038316032,2023-10-11 07:53:36,2023-10-11 08:11:52.332999936,2023-10-11 08:19:52.332999936,2023-10-11 08:27:23.416999936,2023-10-11 08:32:21.333000,NaN
Conductivity,7745.0,33.469233,0.000938,41.815981,41.853163,41.867263,42.017378,16.745639
Temperature,7753.0,17.004214,16.757671,16.921356,16.927819,16.936519,20.959163,0.491434
Pressure,7753.0,11.981235,10.051051,10.282043,11.645332,13.205683,16.381953,1.759088
Sea pressure,7753.0,1.848735,-0.081449,0.149543,1.512832,3.073183,6.249453,1.759088
Depth,7753.0,1.833659,-0.080785,0.148323,1.500495,3.048123,6.198491,1.744743
Salinity,7745.0,25.920174,0.008982,32.379655,32.412544,32.423671,32.553539,12.9662
Speed of sound,7745.0,1502.484581,1471.971069,1509.621248,1509.685891,1509.719982,1509.867941,14.476986
Specific conductivity,7745.0,39564.671517,1.023879,49430.289678,49475.911655,49491.58954,49667.610387,19795.378799
Density anomaly,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df = pd.concat([df7, df11], axis=0)
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Time,11478,2023-10-10 01:22:07.517049088,2023-10-07 08:02:35,2023-10-07 09:03:16.686999808,2023-10-11 08:14:54.624499968,2023-10-11 08:21:16.228999936,2023-10-11 08:32:21.333000,NaN
Conductivity,11463.0,31.711727,0.000938,41.599562,41.855977,41.884886,42.689439,18.084921
Temperature,11478.0,16.84206,13.305192,16.92024,16.930189,17.013338,22.255595,0.977097
Pressure,11478.0,11.750686,10.051051,10.144709,11.350635,12.926369,16.381953,1.644151
Sea pressure,11478.0,1.618186,-0.081449,0.012209,1.218135,2.793869,6.249453,1.644151
Depth,11478.0,1.60499,-0.080785,0.01211,1.208201,2.771086,6.198491,1.630743
Salinity,11463.0,24.520417,0.00801,32.126898,32.415274,32.439687,32.886512,13.980477
Speed of sound,11463.0,1500.29015,1459.898183,1509.526783,1509.695242,1509.778542,1511.296812,17.364803
Specific conductivity,11463.0,37416.562039,1.023879,49083.042179,49479.637074,49514.551592,50122.12613,21336.772233
Density anomaly,3678.0,15.535738,-2.040714,-0.741734,23.693641,23.779536,23.9063,11.589445

In [63]:
df

,Time,Conductivity,Temperature,Pressure,Sea pressure,Depth,Salinity,Speed of sound,Specific conductivity,Density anomaly
0,2023-10-07 08:02:35.000,NaN,22.249984,10.128403,-0.004097,-0.004063,NaN,NaN,NaN,NaN
1,2023-10-07 08:02:35.083,0.001305,22.250450,10.089496,-0.043004,-0.042654,0.010859,1489.073207,1.377450,NaN
2,2023-10-07 08:02:35.167,0.001908,22.250551,10.088925,-0.043575,-0.043220,0.010945,1489.073591,2.013393,NaN
3,2023-10-07 08:02:35.250,0.001493,22.250070,10.088717,-0.043783,-0.043426,0.010881,1489.072122,1.575635,NaN
4,2023-10-07 08:02:35.333,0.001681,22.249732,10.088559,-0.043941,-0.043583,0.010908,1489.071176,1.774381,NaN
...,...,...,...,...,...,...,...,...,...,...
7748,2023-10-11 08:32:21.000,0.004528,16.966380,10.059479,-0.073021,-0.072426,0.009722,1472.667786,5.348005,NaN
7749,2023-10-11 08:32:21.083,0.004490,16.966557,10.059689,-0.072811,-0.072217,0.009708,1472.668363,5.303500,NaN
7750,2023-10-11 08:32:21.166,0.004057,16.967203,10.059540,-0.072960,-0.072365,0.009551,1472.670320,4.791644,NaN
7751,2023-10-11 08:32:21.250,0.003906,16.967822,10.058142,-0.074358,-0.073751,0.009497,1472.672292,4.613647,NaN
7752,2023-10-11 08:32:21.333,0.004678,16.969199,10.060550,-0.071950,-0.071363,0.009779,1472.677252,5.525589,NaN

In [64]:
from matplotlib import pyplot as plt

plt.plot(df['Temperature'], df['Sea pressure'],'r')
plt.plot(df['Salinity'], df['Sea pressure'],'g')

#plt.plot(profile['TEMP2'], profile['PRES'],'g')
plt.gca().invert_yaxis()
plt.xlabel('Temperature [degC]')
plt.ylabel('Pressure [dbar]')

Text(0, 0.5, 'Pressure [dbar]')

In [65]:
from matplotlib import pyplot as plt

# Dados de exemplo
temperature = df['Temperature']
salinity = df['Salinity']
sea_pressure = df['Sea pressure']

# Crie a figura e os eixos
fig, ax1 = plt.subplots(figsize=(8, 6))

# Plote a temperatura no eixo Y invertido
ax1.plot(temperature, sea_pressure, 'r', label='Temperature [degC]')
ax1.set_xlabel('Temperature [degC]')
ax1.set_ylabel('Pressure [dbar]')
ax1.invert_yaxis()  # Inverta o eixo Y para que a pressão seja crescente para baixo

# Crie um segundo eixo compartilhando o mesmo eixo X
ax2 = ax1.twiny()

# Plote a salinidade no eixo X superior
ax2.plot(salinity, sea_pressure, 'g', label='Salinity')
ax2.set_xlabel('Salinity')

# Ajuste os limites dos eixos conforme necessário
ax1.set_xlim(13, 23)  # Limite do eixo X inferior
ax2.set_xlim(30, 33)  # Limite do eixo X superior


plt.title('Temperature and Salinity vs. Pressure')
plt.tight_layout()
plt.show()

#times and profiles 
S1 and S2 total time
S1 = '2023-10-07  08:46:41.000' ; '2023-10-07  08:47:44.000'
S2 = '2023-10-07  08:50:13.000' ; '2023-10-07  08:51:00.000'

S3, S4 and S5 downcasting
S3 = '2023-10-07  08:53:39.000' ; '2023-10-07  08:54:08.000'
S4 = '2023-10-07  08:59:44.000' ; '2023-10-07  09:00:07.000'
S5 = '2023-10-07  09:03:20.000' ; '2023-10-07  09:03:53.667'

S1 - oct 11
2023-10-11  08:09:32.000
2023-10-11  08:11:12.000
S2 oct 11
2023-10-11 08:15:04.333
2023-10-11 08:15:46.167
S3 oct 11
2023-10-11 08:19:25.750
2023-10-11 08:20:33.250
S4 oct 11
2023-10-11 08:26:22.083
2023-10-11 08:27:05.000
S5 oct 11
2023-10-11  08:30:15.083
2023-10-11 08:31:33.333

In [140]:
#each profile, just downcasting
# Defina os limites do intervalo de datas
S1_ti = pd.to_datetime('2023-10-07 09:03:20.000')
S1_tf = pd.to_datetime('2023-10-07 09:03:53.667')

In [141]:
# Defina os limites do intervalo de datas
S2_ti = pd.to_datetime('2023-10-11  08:30:15.083')
S2_tf = pd.to_datetime('2023-10-11 08:31:33.333')

In [142]:
# Filtrar os dados com base no intervalo de datas
S1 = df[(df['Time'] >= S1_ti) & (df['Time'] <= S1_tf)]
S2 = df[(df['Time'] >= S2_ti) & (df['Time'] <= S2_tf)]
# Agora, 'dados_no_intervalo' conterá apenas as linhas com datas dentro do intervalo especific
S2.describe()

,Time,Conductivity,Temperature,Pressure,Sea pressure,Depth,Salinity,Speed of sound,Specific conductivity,Density anomaly
count,940,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,0.0
mean,2023-10-11 08:30:54.208000,41.846865,16.928354,13.027144,2.894644,2.871039,32.407657,1509.695165,49469.694275,NaN
min,2023-10-11 08:30:15.083000,41.549790,16.906068,10.058262,-0.074238,-0.073633,32.162563,1509.325567,49133.097663,NaN
25%,2023-10-11 08:30:34.645249792,41.828116,16.920402,11.307448,1.174948,1.165366,32.395165,1509.648422,49451.524107,NaN
50%,2023-10-11 08:30:54.208000,41.850686,16.922691,12.858418,2.725918,2.703690,32.400436,1509.711779,49459.506800,NaN
75%,2023-10-11 08:31:13.770750208,41.873968,16.925427,14.954161,4.821661,4.782343,32.435562,1509.749685,49508.936087,NaN
max,2023-10-11 08:31:33.333000,41.886907,16.969882,16.381953,6.249453,6.198491,32.443579,1509.781282,49520.431057,NaN
std,NaN,0.033467,0.014620,1.930178,1.930178,1.914438,0.028328,0.063342,39.632830,NaN

In [143]:
from matplotlib import pyplot as plt

plt.plot(S1['Temperature'], S1['Sea pressure'],'r', linestyle='--')
plt.plot(S1['Salinity'], S1['Sea pressure'],'g', linestyle='--')

plt.plot(S2['Temperature'], S2['Sea pressure'],'r')
plt.plot(S2['Salinity'], S2['Sea pressure'],'g')

#plt.plot(profile['TEMP2'], profile['PRES'],'g')
plt.gca().invert_yaxis()
plt.xlabel('Temperature [degC]')
plt.ylabel('Pressure [dbar]')

Text(0, 0.5, 'Pressure [dbar]')

In [144]:
# data
temp1 = S1['Temperature']
temp2 = S2['Temperature']
Sal1 = S1['Salinity']
Sal2 = S2['Salinity']
sp1 = S1['Sea pressure']
sp2 = S2['Sea pressure']

In [146]:
#### Crie a figura e os eixos
fig, ax1 = plt.subplots(figsize=(8, 6))

# Plote a temperatura no eixo Y invertido
ax1.plot(temp1, sp1, 'r', label='Temperature 07-oct [degC]', linestyle='--')
ax1.plot(temp2, sp2, 'r', label='Temperature 11-oct [degC]')
ax1.set_xlabel('Temperature [degC]')
ax1.set_ylabel('Pressure [dbar]')
ax1.invert_yaxis()  # Inverta o eixo Y para que a pressão seja crescente para baixo

# Crie um segundo eixo compartilhando o mesmo eixo X
ax2 = ax1.twiny()

# Plote a salinidade no eixo X superior
ax2.plot(Sal1, sp1, 'g', label='Salinity 07-oct [PSU]', linestyle='--')
ax2.plot(Sal2, sp2, 'g', label='Salinity 11-oct [PSU]')
ax2.set_xlabel('Salinity [PSU]')

# Ajuste os limites dos eixos conforme necessário
ax1.set_xlim(14,17.5)  # Limite do eixo X inferior
ax2.set_xlim(32, 33)  # Limite do eixo X superior

# Adicione a legenda para a temperatura no canto inferior esquerdo
legend1 = ax1.legend(loc='lower left')

# Ajuste a posição da legenda para a salinidade
legend2 = ax2.legend(loc='upper left', bbox_to_anchor=(0.03, 0.23))  # Pode ajustar as coordenadas aqui

# Adicione um texto no gráfico
texto_x = 32.1 # Coordenada X do texto
texto_y = 4.5 # Coordenada Y do texto
texto = "Station 05"  # O texto que você deseja adicionar
plt.text(texto_x, texto_y, texto, fontsize=12, color='black')

plt.tight_layout()
plt.show()

In [120]:
from matplotlib import pyplot as plt

# data
temperature = S['Temperature']
salinity = S['Salinity']
sea_pressure = S['Sea pressure']

# Crie a figura e os eixos
fig, ax1 = plt.subplots(figsize=(8, 6))

# Plote a temperatura no eixo Y invertido
ax1.plot(temperature, sea_pressure, 'r', label='Temperature [degC]')
ax1.set_xlabel('Temperature [degC]')
ax1.set_ylabel('Pressure [dbar]')
ax1.invert_yaxis()  # Inverta o eixo Y para que a pressão seja crescente para baixo

# Crie um segundo eixo compartilhando o mesmo eixo X
ax2 = ax1.twiny()

# Plote a salinidade no eixo X superior
ax2.plot(salinity, sea_pressure, 'g', label='Salinity [PSU]')
ax2.set_xlabel('Salinity [PSU]')

# Ajuste os limites dos eixos conforme necessário
ax1.set_xlim(10,17.5)  # Limite do eixo X inferior
ax2.set_xlim(31, 33)  # Limite do eixo X superior

# Adicione a legenda para a temperatura no canto inferior esquerdo
legend1 = ax1.legend(loc='lower left')

# Ajuste a posição da legenda para a salinidade
legend2 = ax2.legend(loc='upper left', bbox_to_anchor=(0.01, 0.15))  # Pode ajustar as coordenadas aqui

# Adicione um texto no gráfico
texto_x = 31.1 # Coordenada X do texto
texto_y =  2 # Coordenada Y do texto
texto = "Station 01"  # O texto que você deseja adicionar
plt.text(texto_x, texto_y, texto, fontsize=12, color='black')

plt.tight_layout()
plt.show()